---

tasks:
  combinations:
    - filename: main
      files_to_combine:
        - name: main.yml
    - filename: users
      files_to_combine:
        - name: minio/users.yml
    - filename: file-system
      files_to_combine:
        - name: volumes.yml
        - name: directories.yml
    - filename: minio
      files_to_combine:
        - name: minio/minio.yml
        - name: minio/firewall.yml

appendix:
  references:
    - description: Distributed Minio QuickStart Guide
      link: https://docs.min.io/docs/distributed-minio-quickstart-guide.html
    - description: Peter Murphy
      link: https://www.linkedin.com/in/peter-murphy-61493974/
    - description: ansible-mdgen
      link: https://pypi.org/project/ansible-mdgen/


# output_dir: "./docs"
# output_tasks_dir: "tasks"
# output_handlers_dir: "handlers"
# output_defaults_dir: "defaults"
# output_variables_dir: "variables"
# output_files_dir: "files"
# output_templates_dir: "roletemplates"

# output_overwrite: True
# clear_output: True

# output_templates: False
# output_files: False

#transpose_variable_table: True