---
site_name: Minio - Dsitributed Mode
site_description: Role to deploy and configure Minio in distributed mode
theme: mkdocs

nav:
  - index.md
  - Defaults:
    - defaults/main.md
  - Tasks:
    - tasks/main.md
    - tasks/users.md
    - tasks/file-system.md
    - tasks/minio.md
  - Vars:
    - variables/main.md