---
site_name: Minio - Dsitributed Mode
site_description: Role to deploy and configure Minio in distributed mode
theme: mkdocs

# nav:
#   - index.md
#   - Defaults:
#     - defaults/main.md
#   - Tasks:
#     - tasks/main.md
#     - tasks/SDI.md