---
- name: Set proxy server if defined
  set_fact:
    env_proxy: "http://{{ local_proxy.host }}:{{ local_proxy.port }}"
  when: "local_proxy is defined"
  tags: minio

- name: Configure Minio user
  include_tasks: minio/users.yml
  tags: minio,users

- name: Configure logical volumes
  include_tasks: volumes.yml
  when:
    - minio_server_install_volumes is defined
  tags: minio,volumes

- name: Download, Install and Configure Minio
  include_tasks: minio/minio.yml
  tags: minio,install

- name: Configure Firewall
  include_tasks: minio/firewall.yml
  tags: minio,firewall