---
- name: Reload minio systemd
  systemd:
    name: minio
    daemon_reload: True
  listen: "reload minio systemd"

- name: Restart minio
  service:
    name: minio
    state: restarted
  listen: "restart minio"

- name: Reload firewalld service
  systemd:
    name: firewalld
    state: reloaded
  listen: "minio reload firewalld"
  ignore_errors: true