---

- name: Enable firewalld
  service:
    name: firewalld
    state: started
    enabled: yes
  tags: 
    - minio
    - firewall

- name: Open firewall ssh port
  firewalld:
    port: "{{ ansible_ssh_port | default(22) }}/tcp"
    permanent: yes
    state: enabled
  tags: minio,firewall

- name: Open firewall minio ports
  firewalld:
    port: "{{ minio_port }}/tcp"
    permanent: yes
    state: enabled
  notify: "minio reload firewalld"
  tags: minio,firewall