---

- name: "Get the Minio server checksum"
  set_fact:
    minio_server_checksum: "{{ lookup('url', minio_server_download_url + '.sha256sum').split(' ')[0] }}"
  tags: minio,install

# @action Minio-server-install-minio # Download Minio
- name: Download the Minio server
  get_url:
    url: "{{ minio_server_download_url }}"
    dest: "{{ minio_server_bin }}"
    owner: "root"
    group: "root"
    mode: 0755
    checksum: "sha256:{{ minio_server_checksum }}"
  register: _download_server
  until: _download_server is succeeded
  retries: 5
  delay: 2
  notify: restart minio
  environment:
    http_proxy: "{% if env_proxy is defined %}{{ env_proxy }}{% endif %}"
    https_proxy: "{% if env_proxy is defined %}{{ env_proxy }}{% endif %}"
  tags: minio,install

- name: Generate the Minio server envfile
  template:
    src: minio.env.j2
    dest: "{{ minio_server_envfile }}"
    owner: "root"
    group: "{{ minio_group }}"
    mode: 0640
  notify: restart minio
  tags: minio,install

- name: Create the Minio server systemd config
  template:
    src: minio.service.j2
    dest: "/etc/systemd/system/minio.service"
    owner: "root"
    group: "root"
    mode: 0750
  when: ansible_service_mgr == "systemd"
  notify:
    - reload minio systemd
    - restart minio
  tags: minio,install

- name: Create the Minio server init.d config
  template:
    src: minio.init.j2
    dest: "/etc/init.d/minio"
    owner: "root"
    group: "root"
    mode: 0750
  when: ansible_service_mgr != "systemd"
  notify: restart minio
  tags: minio,install

- name: Enable and start the Minio service
  service:
    name: minio
    state: started
    enabled: true
  tags: minio,install