---

- name: Create Minio group
  group:
    name: "{{ minio_group }}"
    state: present
  tags: minio,users

- name: Create Minio user
  user:
    name: "{{ minio_user }}"
    group: "{{ minio_group }}"
    system: "yes"
    shell: "/usr/sbin/nologin"
  tags: minio,users
